// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for sport documents
 */
interface SportDocumentData {
  /**
   * Title field in *sport*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sport.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *sport*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sport.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * featured image field in *sport*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sport.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Published field in *sport*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: sport.published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published: prismic.DateField;
}

/**
 * sport document from Prismic
 *
 * - **API ID**: `sport`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SportDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SportDocumentData>, "sport", Lang>;

/**
 * Content for Trending documents
 */
interface TrendingDocumentData {
  /**
   * Title field in *Trending*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trending.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Trending*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trending.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Published field in *Trending*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: trending.published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  published: prismic.DateField;

  /**
   * Image field in *Trending*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trending.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Trending document from Prismic
 *
 * - **API ID**: `trending`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TrendingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TrendingDocumentData>,
    "trending",
    Lang
  >;

export type AllDocumentTypes = SportDocument | TrendingDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SportDocument,
      SportDocumentData,
      TrendingDocument,
      TrendingDocumentData,
      AllDocumentTypes,
    };
  }
}
